app1/urls.py
from django.urls import path
from app1 import views

app_name = 'app1'

urlpatterns = [
    path('contact/', views.contact, name = 'contact'),
    path('about/', views.about, name = 'about'),
    path('services/', views.services, name = 'services'),
    # <int:pk> will fetch the post with the primary key 
    path('post_detail/<slug:slug>', views.post_detail, name = 'post_detail'),
    path('blog/', views.ListPost.as_view(), name = 'blog'),
    path('test/', views.test, name = 'test'),
    path('dashboard/', views.dashboard, name = 'dashboard'),
    path('base/', views.base, name = 'base')
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from app1 import views
# import settings and static from django.conf 
# in other to set the media root and static url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # path to the admin page 
    path('admin/', admin.site.urls),
    # path to the home page 
    path('', views.index, name = 'home'),
    # path to all app1 urls 
    path('app1/', include('app1.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app1/models.py
from django.db import models
from django.contrib.auth.models import User
# import timezone from django.utils
from django.utils import timezone


# Create your models here.

# The model for user is created here
class UserProfile(models.Model):
    user = models.ForeignKey(User, on_delete =models.CASCADE)
    age = models.IntegerField()
    website = models.URLField(null= True, blank = True)
    def __str__(self):
        return self.user.username

# create a model to save JobCategories
class JobCategories(models.Model):
    job_name = models.CharField(verbose_name='Job Title', max_length=100)
    description = models.TextField(verbose_name='Description', blank=True, null=True)
    def __str__(self):
        return self.job_name

# create a model to save testimonials 
class Testimonial(models.Model):
    testimonial_title = models.CharField(max_length = 150, verbose_name ='Testimonial Title')
    testimonial_name = models.CharField(max_length = 150, verbose_name = 'Testimonial Name')
    testimonial_job = models.ForeignKey(JobCategories, on_delete = models.CASCADE, verbose_name = 'Job Title', blank=True, null=True)
    testimonial_img = models.ImageField(blank = True, null = True, verbose_name = 'Testimonial Image')
    testimonial_contents = models.TextField(verbose_name = 'Testimonial Contents')
    def __str__(self):
        return self.testimonial_title

# Create a model for the post categories 
class PostCategory(models.Model):
    category_name = models.CharField(max_length = 150, verbose_name = 'Category name')
    category_description = models.TextField(verbose_name = 'Description', blank = True, null = True)
    def __str__(self):
        return self.category_name


STATUS = (
    (0, "Draft"),
    (1, "Publish")
)
# create a model to post on blog 
class BlogPost(models.Model):
    post_title = models.CharField(max_length =150, verbose_name = 'Post Title')
    slug = models.SlugField(max_length=200, unique=True, blank = True, null = True)
    post_author = models.ForeignKey(User, on_delete = models.CASCADE, verbose_name= 'Author')
    post_category = models.ForeignKey(PostCategory, on_delete = models.CASCADE, verbose_name = 'Post Category')
    post_img = models.ImageField(blank = True, null = True, verbose_name = 'Post Featured Image')
    created_date = models.DateTimeField(default = timezone.now)
    updated_on = models.DateTimeField(auto_now=True, blank = True, null = True)
    post_contents = models.TextField(verbose_name = 'Post Contents')
    status = models.IntegerField(choices=STATUS, default=0, blank = True, null = True)
    class Meta:
        ordering  = ['-created_date']
    def __str__(self):
        return self.post_title

# create a model for comment 
class Comment(models.Model):
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    liked = models.ManyToManyField(User, blank=True, related_name='likes')
    created_on = models.DateTimeField(auto_now_add = True)
    active = models.BooleanField(default=False)
    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

# create a tuple to use in the CommentLike model 
LIKE_CHOICES=(
    ('Like', 'Like'),
    ('Unlike', 'Unlike')
)
# create a model called comment like 
class CommentLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete = models.CASCADE)
    value = models.CharField(choices=LIKE_CHOICES, max_length=8)
    created_on = models.DateTimeField(auto_now_add = True)
    updated_on = models.DateTimeField(auto_now_add = True)
    def __str__(self):
        return f"{self.user}-{self.comment}-{self.value}"

# create a model to add services 
class AddService(models.Model):
    service_title = models.CharField(max_length = 150, verbose_name = "Service Title")
    service_img = models.ImageField(verbose_name = "Post Service Image")
    service_contents = models.TextField(verbose_name = "Service Contents")

    def __str__(self):
        return self.service_title

# create a model for site settings 
class SiteSetting(models.Model):
    site_name = models.CharField(max_length = 150, verbose_name = "Site Name")
    site_logo = models.ImageField(verbose_name = "Site Logo", blank = True, null = True)
    site_address = models.TextField(verbose_name = "Company Address", blank = True, null = True)
    site_phone = models.CharField(max_length = 150, verbose_name = "Company Phone Number", blank = True, null = True)
    site_email1 = models.EmailField(max_length = 254, verbose_name = "Company Email", blank = True, null = True)
    site_email2 = models.EmailField(max_length = 254, verbose_name = "Customer Service Email", blank = True, null = True)
    def __str__(self):
        return self.site_name

class Contact(models.Model):
    contact_name = models.CharField(max_length =150, verbose_name ="Name")
    contact_email = models.EmailField(max_length = 150, verbose_name = "Email Address")
    contact_subject = models.CharField(max_length = 150, verbose_name = "Subject")
    contact_contents = models.TextField(verbose_name = "Contact Message")

app1/forms.py
from django import forms
from app1.models import Contact, Comment

# class PostForm(forms.ModelForm):
#     class Meta():
#         model = Post
#         # __all__ will fetch all the form in the Post model in our models.py 
#         fields = "__all__"

class ContactForm(forms.ModelForm):
    contact_name = forms.CharField(widget = forms.TextInput(attrs={'placeholder': 'Enter Full Name', 'class': 'contact-input', 'id': 'w3lName', 'required': "false"} ))
    contact_email = forms.EmailField(widget = forms.TextInput(attrs={'placeholder': 'Enter Email', 'class': 'contact-input', 'id': 'w3lName'} ))
    contact_subject = forms.CharField(widget = forms.TextInput(attrs={'placeholder': 'Enter Subject', 'class': 'contact-input', 'id': 'w3lName'} ))
    contact_contents = forms.CharField(widget = forms.Textarea(attrs={'placeholder': 'Enter Contents', 'id': 'w3lMessage', 'rows': 3} ))
    class Meta():
        model = Contact
        fields = ('contact_name', 'contact_email', 'contact_subject', 'contact_contents')

class CommentForm(forms.ModelForm):
    name = forms.CharField(widget = forms.TextInput(attrs={'placeholder': 'Enter Name', 'class': 'form-control mb-4'}))
    email = forms.CharField(widget = forms.TextInput(attrs={'placeholder': 'Email Address', 'class': 'form-control mb-4'}))
    body = forms.CharField(widget = forms.Textarea(attrs={'placeholder': 'Your message', 'class': 'form-control'}))
    class Meta:
        model = Comment 
        fields = ('name', 'email', 'body')
        

app1/views.py
from django.shortcuts import render, get_object_or_404
# import the Testimonial model from models.py in app1 
from app1.models import Testimonial, BlogPost, AddService, Comment
# import ListView and DetailView  from django.views.generic 
from django.views.generic import ListView, DetailView
# import contact form from the forms.py in the app1 
from app1.forms import ContactForm, CommentForm
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib import messages
from django.http import HttpResponseRedirect

# Create your views here.
def index(request):
    service = AddService.objects.all()
    testimonial = Testimonial.objects.all()
    # filter by published post, created date and number of posts 
    blog = BlogPost.objects.filter(status=1).order_by('-created_date')[:2]
    return render(request, 'app1/index.html', {"testimonial": testimonial,
                                                "blog": blog, 
                                                "service": service
                                                })
def contact(request):
    if request.method == "POST":
        contactform = ContactForm(request.POST)
        if contactform.is_valid():
            contactform.save(commit=True)
            messages.success(request, "Message successfully submitted!")
            return HttpResponseRedirect('/app1/contact')
        else:
            messages.error(request, "Message not submitted!")
    else:
        contactform = ContactForm()
    return render(request, 'app1/contact.html', {"contactform": contactform})
    
def about(request):
    testimonial = Testimonial.objects.all()
    return render(request, 'app1/about.html', {"testimonial": testimonial})
def services(request):
    service = AddService.objects.all()
    return render(request, 'app1/services.html', {"service": service})
def test(request):
    blog = BlogPost.objects.all()
    return render(request, 'app1/test.html', {"blog": blog})


# the ListPost view will list out all the post 
class ListPost(ListView):
    model = BlogPost
    queryset = BlogPost.objects.filter(status=1).order_by('-created_date')
    template_name = 'app1/blog.html'
    context_object_name = 'post_list'
    
# the post_detail view will display the post based on the id of the post 
def post_detail(request, slug):
    template_name = 'app1/detail_post.html'
    post = get_object_or_404(BlogPost, slug=slug)
    comments = post.comments.filter(active=True)
    new_comment = None 
    # comment posted 
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():

            # create comment object but don't save to database yet 
            new_comment = comment_form.save(commit=False)
            # assign the current post to the comment 
            new_comment.post = post
            # save the comment to the database 
            new_comment.save()
            # sweetify.success(request, 'Comment successfully submitted!')
            messages.success(request, "Comment successfully submitted! Your comment will appear once approved.")
            return HttpResponseRedirect('/app1/post_detail/' + post.slug )
        else:
            messages.error(request, "Comment not submitted.")         
    else:
        comment_form = CommentForm()
    
    return render(request, template_name, {'post': post,
                                           'comments': comments,
                                           'new_comment': new_comment,
                                           'comment_form': comment_form})


# DASHBOARD VIEW
def dashboard(request):
    return render(request, 'app1/dashboard/index.html')

def base(request):
    return render(request, 'app1/dashboard/base.html')

templates/app1/includes/blog.html
{% load static %}


{% if blog %}
<div class="w3l-blog-content py-5">
    <div class="container py-md-5 py-4">
        <div class="title-main text-center mx-auto mb-5" style="max-width:600px;">
            <p class="mt-2">Our Blog</p>
            <h3 class="title-style">Learn more from our latest <span>Blog</span> Posts</h3>
        </div>
        <div class="row">
            
                {% for p in blog %}
            <div class="col-md-6">
                <div class="card-header p-0 position-relative">
                    <a href="{% url 'app1:post_detail' p.slug %}" class="zoom d-block">
                        <img class="card-img-bottom d-block" src="{{ p.post_img.url }}" alt="Card image cap">
                    </a>
                    <div class="course-price-badge">{{ p.post_category }}</div>
                </div>
                <div class="card-body course-details">
                    <div class="course-meta mb-3">
                        <div class="meta-item course-students">
                            <a href="#author"><span class="fas fa-user"></span>
                                <span class="meta-value"></span>{{ p.post_author }}</a>
                        </div>
                        <div class="meta-item course-lesson">
                            <span class="fa fa-heart"></span>
                            <span class="meta-value"> 24 </span>
                        </div>
                        <div class="meta-item course-students">
                            <span class="fa fa-calendar"></span>
                            <span class="meta-value">{{ p.created_date }}</span>
                        </div>
                    </div>
                    <a href="{% url 'app1:post_detail' p.slug %}" class="course-desc">{{ p.post_title }}</a>
                    <!-- <p class="mt-3">{{ p.post_contents|truncatewords:30 }}</p> -->
                    <p class="mt-3">{{ p.post_contents|slice:100 }}</p>
                    <div class="blog-bottom-info">
                        <a href="{% url 'app1:post_detail' p.slug %}" class="btn btn-style">Read more</a>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</div>

templates/app1/includes/contact.html
<div class="contact-form-sec pt-5 mt-md-5">
    <div class="title-heading-w3 text-center mx-auto mb-5 pb-sm-4" style="max-width:600px">
        <h3 class="title-style">We will Answer all your <span>Questions</span></h3>
    </div>
    <div class="row contact-block align-items-center">
        <div class="col-md-9 contact-right mt-md-0 mt-4 pl-lg-4 m-auto">
            <form method="post" class="signin-form">
                
                <div class="input-grids">
                    {{contactform.contact_name}}
                    {{contactform.contact_email}}
                    {{contactform.contact_subject}}
                </div>
                <div class="form-input">
                    <!-- <textarea name="w3lMessage" id="w3lMessage" placeholder="Type your message here*"
                        required=""></textarea> -->
                    {{contactform.contact_contents}}
                    {% csrf_token %}
                </div>
                <button class="btn btn-style mt-sm-3">Send Message</button>

            </form>
        </div>
    </div>
</div>

templates/app1/includes/footer.html
<footer class="w3l-footer-29-main">
    <div class="footer-29-w3l py-5">
        <div class="container py-4">
            <div class="row footer-top-29">
                <div class="col-lg-4 col-md-6 col-sm-7 footer-list-29 footer-1 pr-lg-5">
                    <div class="footer-logo mb-3">
                        <a class="footer-brand-logo" href="{% url 'home' %}"><i class="fas fa-tools mr-1"
                                aria-hidden="true"></i>Industries</a>
                    </div>
                    <p>Lorem ipsum viverra feugiat. Pellen tesque libero ut justo, ultrices in ligula.
                        Semper at
                        tempufddfel. Lorem ipsum dolor sit amet Semper at elit.</p>
                    <div class="main-social-footer-29 mt-4">
                        <a href="#facebook" class="facebook"><span class="fab fa-facebook-f"></span></a>
                        <a href="#twitter" class="twitter"><span class="fab fa-twitter"></span></a>
                        <a href="#instagram" class="instagram"><span class="fab fa-instagram"></span></a>
                        <a href="#linkedin" class="linkedin"><span class="fab fa-linkedin-in"></span></a>
                    </div>
                </div>
                <div class="col-lg-2 col-md-6 col-sm-5 col-6 footer-list-29 footer-2 mt-sm-0 mt-5">
                    <ul>
                        <h6 class="footer-title-29">Usefull Links</h6>
                        <li><a href="{% url 'home' %}">Home</a></li>
                        <li><a href="{% url 'app1:about' %}">About Us</a></li>
                        <li><a href="#careers">Services</a></li>
                        <li><a href="#blog">Blog Posts</a></li>
                        <li class="mb-0"><a href="{% url 'app1:contact' %}">Contact us</a></li>
                    </ul>
                </div>
                <div class="col-lg-2 col-md-6 col-sm-5 col-6 footer-list-29 footer-3 mt-lg-0 mt-5 pl-lg-4">
                    <h6 class="footer-title-29">More Info</h6>
                    <ul>
                        <li><a href="#support">Support</a></li>
                        <li><a href="#privacy">Privacy Policy</a></li>
                        <li><a href="#terms">Terms & conditions</a></li>
                        <li><a href="#help">Help</a></li>
                    </ul>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-7 footer-list-29 footer-4 mt-lg-0 mt-5 pl-lg-5">
                    <h6 class="footer-title-29">Newsletter </h6>
                    <form action="#" class="subscribe d-flex align-items-center" method="post">
                        <input type="email" name="email" placeholder="Email Address" required="">
                        <button><span class="fa fa-paper-plane" aria-hidden="true"></span></button>
                    </form>
                    <h6 class="footer-title-29 pt-2 mt-4 mb-3">Give us a free call: </h6>
                    <a href="tel:+12 23456790">+12 23456790</a>
                </div>
            </div>
        </div>
    </div>
    <!-- copyright -->
    <div class="w3l-copyright">
        <div class="container">
            <div class="row bottom-copies align-items-center">
                <p class="col-lg-8 copy-footer-29">@ 2021 Industries. All rights reserved. Design by <a
                        href="https://w3layouts.com/" target="_blank">
                        W3Layouts</a></p>
                <div class="col-lg-4 footer-list-29 footer-copy-list">
                    <ul class="text-lg-right">
                        <li><a href="#careers"> Careers</a></li>
                        <li class="mx-lg-5 mx-md-4 mx-3"><a href="#faq">FAQ</a></li>
                        <li><a href="{% url 'app1:contact' %}">Contact us</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/app1/includes/list_post.html
{% load static %}

<div class="w3l-blog-content py-5">
    <div class="container py-md-5 py-4">
       
        <div class="row">
            {% if post_list %}
            {% for p in post_list %}    
            <div class="col-md-8 mb-5">
                <div class="title-main text-center mx-auto mb-5" style="max-width:600px;">
                    <p class="mt-2">Our Blog</p>
                    <h3 class="title-style">Learn more from our latest <span>Blog</span> Posts</h3>
                </div>
                <div class="card-header p-0 position-relative">
                    <a href="{% url 'app1:post_detail' p.slug %}" class="zoom d-block">
                        <img class="card-img-bottom d-block" src="{{ p.post_img.url }}" alt="Card image cap">
                    </a>
                    <div class="course-price-badge">{{ p.post_category }}</div>
                </div>
                <div class="card-body course-details">
                    <div class="course-meta mb-3">
                        <div class="meta-item course-students">
                            <a href="#author"><span class="fas fa-user"></span>
                                <span class="meta-value"></span>{{ p.post_author }}</a>
                        </div>
                        <div class="meta-item course-lesson">
                            <span class="fa fa-heart"></span>
                            <span class="meta-value"> 24 </span>
                        </div>
                        <div class="meta-item course-students">
                            <span class="fa fa-calendar"></span>
                            <span class="meta-value">{{ p.created_date }}</span>
                        </div>
                    </div>
                    <a href="{% url 'app1:post_detail' p.slug %}" class="course-desc">{{ p.post_title }}</a>
                    <!-- <p class="mt-3">{{ p.post_contents|truncatewords:30 }}</p> -->
                    <p class="mt-3">{{ p.post_contents|slice:100 }}</p>
                    <div class="blog-bottom-info">
                        <a href="{% url 'app1:post_detail' p.slug %}" class="btn btn-style">Read more</a>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</div>

templates/app1/includes/nav.html
<header id="site-header" class="fixed-top">
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg stroke">
            <h1>
                <a class="navbar-brand d-flex align-items-center" href="{% url 'home' %}">
                    <i class="fas fa-tools mr-1" aria-hidden="true"></i>Industries</a>
            </h1>
            <!-- if logo is image enable this   
<a class="navbar-brand" href="#index.html">
    <img src="image-path" alt="Your logo" title="Your logo" style="height:35px;" />
</a> -->
            <button class="navbar-toggler  collapsed bg-gradient" type="button" data-toggle="collapse"
                data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon fa icon-expand fa-bars"></span>
                <span class="navbar-toggler-icon fa icon-close fa-times"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav ml-lg-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app1:about' %}">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app1:services' %}">Services</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'app1:contact' %}">Contact Us</a>
                    </li>
                        <a class="nav-link" href="{% url 'app1:blog' %}">Blog</a>
                    </li>
                    <!-- search button -->
                    <div class="search-right ml-lg-3">
                        <form action="#search" method="GET" class="search-box position-relative">
                            <div class="input-search">
                                <input type="search" placeholder="Enter Keyword" name="search" required="required"
                                    autofocus="" class="search-popup">
                            </div>
                            <button type="submit" class="btn search-btn"><i class="fa fa-search"
                                    aria-hidden="true"></i></button>
                        </form>
                    </div>
                    <!-- //search button -->
                </ul>
            </div>
            <!-- toggle switch for light and dark theme -->
            <div class="cont-ser-position">
                <nav class="navigation">
                    <div class="theme-switch-wrapper">
                        <label class="theme-switch" for="checkbox">
                            <input type="checkbox" id="checkbox">
                            <div class="mode-container">
                                <i class="gg-sun"></i>
                                <i class="gg-moon"></i>
                            </div>
                        </label>
                    </div>
                </nav>
            </div>
            <!-- //toggle switch for light and dark theme -->
        </nav>
    </div>
</header>

templates/app1/includes/services.html
{% load static %}
{% if service %}
<section class="w3l-bottom-grids-6 py-5" id="services">
    <div class="container py-md-5 py-4">
        <div class="title-main text-center mx-auto mb-5" style="max-width:600px;">
            <p class="mt-2">Our Services</p>
            <h3 class="title-style">High Performance Services For Multiple <span>Industries</span></h3>
        </div>
        <div class="row pt-md-4">
            {% for s in service %}
            <div class="col-lg-4 col-md-6 grids-feature">
                <div class="area-box">
                    <img class="img-fluid" src="{{ s.service_img.url }}" alt=" ">
                    <h4><a href="#feature" class="title-head">{{ s.service_title }}</a></h4>
                    <p>{{ s.service_contents | truncatechars:100 }}</p>
                </div>
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</section>

templates/app1/includes/testimonial.html
{% load static %}

<!-- create an if block  -->

<section class="w3l-clients py-5 mb-5 mt-4" id="testimonials">
    <div class="container py-md-5 py-4">
        <div class="title-main text-center mx-auto mb-5" style="max-width:600px;">
            <p class="mt-2">Testimonials</p>
            <h3 class="title-style">Happy WIth Customers & <span>Clients</span>
            </h3>
        </div>
        <div id="owl-demo2" class="owl-carousel owl-theme mt-4 py-md-2 mb-md-4">
{% if testimonial %}
{% for t in testimonial %}            
            <div class="item">
                <div class="testimonial-content">
                    <div class="testimonial">
                        <blockquote>
                            <q>{{ t.testimonial_title }}</q>
                        </blockquote>
                        <p>{{ t.testimonial_contents }}</p>
                    </div>
                    <div class="bottom-info mt-4">
                        <a class="comment-img" href="#url"><img src="{{ t.testimonial_img.url }}"
                                class="img-responsive" alt="placeholder image"></a>
                        <div class="people-info align-self">
                            <h3>{{ t.testimonial_name }}</h3>
                            <p class="identity">{{ t.testimonial_job }}</p>
                        </div>
                    </div>
                </div>
            </div>
{% endfor %}
{% endif %}
        </div>
    </div>
</section>